version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node
    environment:
      AWS_REGION: eu-central-1
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - setup_remote_docker:
          from: dist
          to: 's3://pawzie/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
  build-staging:
    docker:
      - image: circleci/python:2.7-node
    environment:
      AWS_REGION: us-east-1
    steps:
      - checkout
      - run: npm install
      - run: npm run build:staging
      - setup_remote_docker:
          from: dist
          to: 's3://pawzie/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
  build-staging:
    jobs:
      - build-staging:
          filters:
            branches:
              only: develop